//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteJeBouniqueV_2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderP
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string CodePostal { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
